syntax = "proto3";

package fr.lirmm.bridge;

option java_multiple_files = true;
option java_package = "fr.lirmm.bridge";
option java_outer_classname = "BridgeProto";

service BridgeService {
  // Exécution standard d'une fonction Python via JSON
  rpc Execute (FunctionCall) returns (FunctionResult) {}
}

message FunctionCall {
    string function_name = 1;
    string args_json = 2; // Arguments sérialisés en JSON
}

message FunctionResult {
    bool success = 1;      // True si l'exécution a réussi
    string result_json = 2; // Résultat en JSON
    string error_message = 3; // Message d'erreur en cas d'échec
}
