// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge.proto

// Protobuf Java Version: 3.25.1
package fr.lirmm.bridge.grpc;

public final class BridgeProto {
  private BridgeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fr_lirmm_bridge_grpc_FunctionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fr_lirmm_bridge_grpc_FunctionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fr_lirmm_bridge_grpc_FunctionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fr_lirmm_bridge_grpc_FunctionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fr_lirmm_bridge_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fr_lirmm_bridge_grpc_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fr_lirmm_bridge_grpc_FunctionList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fr_lirmm_bridge_grpc_FunctionList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014bridge.proto\022\024fr.lirmm.bridge.grpc\";\n\017" +
      "FunctionRequest\022\025\n\rfunction_name\030\001 \001(\t\022\021" +
      "\n\targs_json\030\002 \001(\t\"O\n\020FunctionResponse\022\017\n" +
      "\007success\030\001 \001(\010\022\023\n\013result_json\030\002 \001(\t\022\025\n\re" +
      "rror_message\030\003 \001(\t\"\007\n\005Empty\"&\n\014FunctionL" +
      "ist\022\026\n\016function_names\030\001 \003(\t2\277\001\n\rBridgeSe" +
      "rvice\022Z\n\007Execute\022%.fr.lirmm.bridge.grpc." +
      "FunctionRequest\032&.fr.lirmm.bridge.grpc.F" +
      "unctionResponse\"\000\022R\n\rListFunctions\022\033.fr." +
      "lirmm.bridge.grpc.Empty\032\".fr.lirmm.bridg" +
      "e.grpc.FunctionList\"\000B%\n\024fr.lirmm.bridge" +
      ".grpcB\013BridgeProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fr_lirmm_bridge_grpc_FunctionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fr_lirmm_bridge_grpc_FunctionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fr_lirmm_bridge_grpc_FunctionRequest_descriptor,
        new java.lang.String[] { "FunctionName", "ArgsJson", });
    internal_static_fr_lirmm_bridge_grpc_FunctionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fr_lirmm_bridge_grpc_FunctionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fr_lirmm_bridge_grpc_FunctionResponse_descriptor,
        new java.lang.String[] { "Success", "ResultJson", "ErrorMessage", });
    internal_static_fr_lirmm_bridge_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fr_lirmm_bridge_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fr_lirmm_bridge_grpc_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_fr_lirmm_bridge_grpc_FunctionList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_fr_lirmm_bridge_grpc_FunctionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fr_lirmm_bridge_grpc_FunctionList_descriptor,
        new java.lang.String[] { "FunctionNames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
