// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge.proto

// Protobuf Java Version: 3.25.1
package fr.lirmm.bridge.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fr.lirmm.bridge.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
