// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge.proto

// Protobuf Java Version: 3.25.1
package fr.lirmm.bridge.grpc;

/**
 * Protobuf type {@code fr.lirmm.bridge.grpc.FunctionList}
 */
public final class FunctionList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fr.lirmm.bridge.grpc.FunctionList)
    FunctionListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FunctionList.newBuilder() to construct.
  private FunctionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FunctionList() {
    functionNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FunctionList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fr.lirmm.bridge.grpc.BridgeProto.internal_static_fr_lirmm_bridge_grpc_FunctionList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fr.lirmm.bridge.grpc.BridgeProto.internal_static_fr_lirmm_bridge_grpc_FunctionList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fr.lirmm.bridge.grpc.FunctionList.class, fr.lirmm.bridge.grpc.FunctionList.Builder.class);
  }

  public static final int FUNCTION_NAMES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList functionNames_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string function_names = 1;</code>
   * @return A list containing the functionNames.
   */
  public com.google.protobuf.ProtocolStringList
      getFunctionNamesList() {
    return functionNames_;
  }
  /**
   * <code>repeated string function_names = 1;</code>
   * @return The count of functionNames.
   */
  public int getFunctionNamesCount() {
    return functionNames_.size();
  }
  /**
   * <code>repeated string function_names = 1;</code>
   * @param index The index of the element to return.
   * @return The functionNames at the given index.
   */
  public java.lang.String getFunctionNames(int index) {
    return functionNames_.get(index);
  }
  /**
   * <code>repeated string function_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the functionNames at the given index.
   */
  public com.google.protobuf.ByteString
      getFunctionNamesBytes(int index) {
    return functionNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < functionNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, functionNames_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < functionNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(functionNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFunctionNamesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fr.lirmm.bridge.grpc.FunctionList)) {
      return super.equals(obj);
    }
    fr.lirmm.bridge.grpc.FunctionList other = (fr.lirmm.bridge.grpc.FunctionList) obj;

    if (!getFunctionNamesList()
        .equals(other.getFunctionNamesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFunctionNamesCount() > 0) {
      hash = (37 * hash) + FUNCTION_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionNamesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static fr.lirmm.bridge.grpc.FunctionList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static fr.lirmm.bridge.grpc.FunctionList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fr.lirmm.bridge.grpc.FunctionList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fr.lirmm.bridge.grpc.FunctionList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fr.lirmm.bridge.grpc.FunctionList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fr.lirmm.bridge.grpc.FunctionList)
      fr.lirmm.bridge.grpc.FunctionListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.lirmm.bridge.grpc.BridgeProto.internal_static_fr_lirmm_bridge_grpc_FunctionList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.lirmm.bridge.grpc.BridgeProto.internal_static_fr_lirmm_bridge_grpc_FunctionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.lirmm.bridge.grpc.FunctionList.class, fr.lirmm.bridge.grpc.FunctionList.Builder.class);
    }

    // Construct using fr.lirmm.bridge.grpc.FunctionList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      functionNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fr.lirmm.bridge.grpc.BridgeProto.internal_static_fr_lirmm_bridge_grpc_FunctionList_descriptor;
    }

    @java.lang.Override
    public fr.lirmm.bridge.grpc.FunctionList getDefaultInstanceForType() {
      return fr.lirmm.bridge.grpc.FunctionList.getDefaultInstance();
    }

    @java.lang.Override
    public fr.lirmm.bridge.grpc.FunctionList build() {
      fr.lirmm.bridge.grpc.FunctionList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fr.lirmm.bridge.grpc.FunctionList buildPartial() {
      fr.lirmm.bridge.grpc.FunctionList result = new fr.lirmm.bridge.grpc.FunctionList(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fr.lirmm.bridge.grpc.FunctionList result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        functionNames_.makeImmutable();
        result.functionNames_ = functionNames_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fr.lirmm.bridge.grpc.FunctionList) {
        return mergeFrom((fr.lirmm.bridge.grpc.FunctionList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fr.lirmm.bridge.grpc.FunctionList other) {
      if (other == fr.lirmm.bridge.grpc.FunctionList.getDefaultInstance()) return this;
      if (!other.functionNames_.isEmpty()) {
        if (functionNames_.isEmpty()) {
          functionNames_ = other.functionNames_;
          bitField0_ |= 0x00000001;
        } else {
          ensureFunctionNamesIsMutable();
          functionNames_.addAll(other.functionNames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFunctionNamesIsMutable();
              functionNames_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList functionNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFunctionNamesIsMutable() {
      if (!functionNames_.isModifiable()) {
        functionNames_ = new com.google.protobuf.LazyStringArrayList(functionNames_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @return A list containing the functionNames.
     */
    public com.google.protobuf.ProtocolStringList
        getFunctionNamesList() {
      functionNames_.makeImmutable();
      return functionNames_;
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @return The count of functionNames.
     */
    public int getFunctionNamesCount() {
      return functionNames_.size();
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @param index The index of the element to return.
     * @return The functionNames at the given index.
     */
    public java.lang.String getFunctionNames(int index) {
      return functionNames_.get(index);
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the functionNames at the given index.
     */
    public com.google.protobuf.ByteString
        getFunctionNamesBytes(int index) {
      return functionNames_.getByteString(index);
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @param index The index to set the value at.
     * @param value The functionNames to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionNames(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFunctionNamesIsMutable();
      functionNames_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @param value The functionNames to add.
     * @return This builder for chaining.
     */
    public Builder addFunctionNames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFunctionNamesIsMutable();
      functionNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @param values The functionNames to add.
     * @return This builder for chaining.
     */
    public Builder addAllFunctionNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureFunctionNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, functionNames_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionNames() {
      functionNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_names = 1;</code>
     * @param value The bytes of the functionNames to add.
     * @return This builder for chaining.
     */
    public Builder addFunctionNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFunctionNamesIsMutable();
      functionNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fr.lirmm.bridge.grpc.FunctionList)
  }

  // @@protoc_insertion_point(class_scope:fr.lirmm.bridge.grpc.FunctionList)
  private static final fr.lirmm.bridge.grpc.FunctionList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fr.lirmm.bridge.grpc.FunctionList();
  }

  public static fr.lirmm.bridge.grpc.FunctionList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FunctionList>
      PARSER = new com.google.protobuf.AbstractParser<FunctionList>() {
    @java.lang.Override
    public FunctionList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FunctionList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FunctionList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fr.lirmm.bridge.grpc.FunctionList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

