// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge.proto

// Protobuf Java Version: 3.25.1
package fr.lirmm.bridge.grpc;

public interface FunctionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fr.lirmm.bridge.grpc.FunctionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string function_name = 1;</code>
   * @return The functionName.
   */
  java.lang.String getFunctionName();
  /**
   * <code>string function_name = 1;</code>
   * @return The bytes for functionName.
   */
  com.google.protobuf.ByteString
      getFunctionNameBytes();

  /**
   * <pre>
   * Arguments serialized as JSON list/object
   * </pre>
   *
   * <code>string args_json = 2;</code>
   * @return The argsJson.
   */
  java.lang.String getArgsJson();
  /**
   * <pre>
   * Arguments serialized as JSON list/object
   * </pre>
   *
   * <code>string args_json = 2;</code>
   * @return The bytes for argsJson.
   */
  com.google.protobuf.ByteString
      getArgsJsonBytes();
}
