// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge.proto

// Protobuf Java Version: 3.25.1
package fr.lirmm.bridge.grpc;

public interface FunctionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fr.lirmm.bridge.grpc.FunctionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * Result serialized as JSON
   * </pre>
   *
   * <code>string result_json = 2;</code>
   * @return The resultJson.
   */
  java.lang.String getResultJson();
  /**
   * <pre>
   * Result serialized as JSON
   * </pre>
   *
   * <code>string result_json = 2;</code>
   * @return The bytes for resultJson.
   */
  com.google.protobuf.ByteString
      getResultJsonBytes();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
