// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridge.proto

// Protobuf Java Version: 3.25.1
package fr.lirmm.bridge.grpc;

public interface FunctionListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fr.lirmm.bridge.grpc.FunctionList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string function_names = 1;</code>
   * @return A list containing the functionNames.
   */
  java.util.List<java.lang.String>
      getFunctionNamesList();
  /**
   * <code>repeated string function_names = 1;</code>
   * @return The count of functionNames.
   */
  int getFunctionNamesCount();
  /**
   * <code>repeated string function_names = 1;</code>
   * @param index The index of the element to return.
   * @return The functionNames at the given index.
   */
  java.lang.String getFunctionNames(int index);
  /**
   * <code>repeated string function_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the functionNames at the given index.
   */
  com.google.protobuf.ByteString
      getFunctionNamesBytes(int index);
}
