# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\x14\x66r.lirmm.bridge.grpc\";\n\x0f\x46unctionRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x11\n\targs_json\x18\x02 \x01(\t\"O\n\x10\x46unctionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"&\n\x0c\x46unctionList\x12\x16\n\x0e\x66unction_names\x18\x01 \x03(\t2\xbf\x01\n\rBridgeService\x12Z\n\x07\x45xecute\x12%.fr.lirmm.bridge.grpc.FunctionRequest\x1a&.fr.lirmm.bridge.grpc.FunctionResponse\"\x00\x12R\n\rListFunctions\x12\x1b.fr.lirmm.bridge.grpc.Empty\x1a\".fr.lirmm.bridge.grpc.FunctionList\"\x00\x42%\n\x14\x66r.lirmm.bridge.grpcB\x0b\x42ridgeProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024fr.lirmm.bridge.grpcB\013BridgeProtoP\001'
  _globals['_FUNCTIONREQUEST']._serialized_start=38
  _globals['_FUNCTIONREQUEST']._serialized_end=97
  _globals['_FUNCTIONRESPONSE']._serialized_start=99
  _globals['_FUNCTIONRESPONSE']._serialized_end=178
  _globals['_EMPTY']._serialized_start=180
  _globals['_EMPTY']._serialized_end=187
  _globals['_FUNCTIONLIST']._serialized_start=189
  _globals['_FUNCTIONLIST']._serialized_end=227
  _globals['_BRIDGESERVICE']._serialized_start=230
  _globals['_BRIDGESERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
