# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bridge_pb2 as bridge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/fr.lirmm.bridge.grpc.BridgeService/Execute',
                request_serializer=bridge__pb2.FunctionRequest.SerializeToString,
                response_deserializer=bridge__pb2.FunctionResponse.FromString,
                _registered_method=True)
        self.ListFunctions = channel.unary_unary(
                '/fr.lirmm.bridge.grpc.BridgeService/ListFunctions',
                request_serializer=bridge__pb2.Empty.SerializeToString,
                response_deserializer=bridge__pb2.FunctionList.FromString,
                _registered_method=True)


class BridgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Execute a function by name with JSON arguments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFunctions(self, request, context):
        """List available functions (for discovery)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=bridge__pb2.FunctionRequest.FromString,
                    response_serializer=bridge__pb2.FunctionResponse.SerializeToString,
            ),
            'ListFunctions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFunctions,
                    request_deserializer=bridge__pb2.Empty.FromString,
                    response_serializer=bridge__pb2.FunctionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fr.lirmm.bridge.grpc.BridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fr.lirmm.bridge.grpc.BridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BridgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fr.lirmm.bridge.grpc.BridgeService/Execute',
            bridge__pb2.FunctionRequest.SerializeToString,
            bridge__pb2.FunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFunctions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fr.lirmm.bridge.grpc.BridgeService/ListFunctions',
            bridge__pb2.Empty.SerializeToString,
            bridge__pb2.FunctionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
